service: ideasgrab-discord-bot
app: ideasgrab-discord-bot

frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-2
  runtime: python3.9
  stage: prod
	
custom:
  pythonRequirements:
    usePoetry: true
    dockerizePip: true
    modifyPackageInclude: false
	
package:
  patterns:
    - '!./**'
    - 'src/main.py'

functions:
  rateHandler:
    handler: src.main.main
    events:
      - schedule: rate(1 minute)
    logRetentionInDays: 7

plugins:
  - serverless-python-requirements
  - serverless-plugin-log-retention
