# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  one:
    docker:
      - image: cimg/python:3.9
    executor: serverless/default
    steps:
    - uses: actions/checkout@v3
    - uses: serverless/github-action@v3.1
      with:
        args: -c "serverless plugin install --name serverless-python-requirements && serverless plugin install --name serverless-plugin-log-retention && serverless deploy"
        entrypoint: /bin/sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
